### ISSUE TITLE
Project name collision

### ISSUE THREAD

**Issue by metaloha** [clio-lang/clio#193]
Aloha!

I'm not sure if you're aware, but there is a company that operates under the name Clio already, and while the focus is different (legal software as opposed to a programming language), there might eventually be confusion. Forcing people to search "clio lang" whenever they're looking for something specific to this project seems like extra work that shouldn't need to exist.

No CTA here, just a heads up.

**Comment by ronangaillard** [comment]
It's also a famous car name it might also be a problem when googling "Clio"

**Comment by pouya-eghbali** [comment]
@metaloha @ronangaillard do you guys have any suggestions? My wife suggested ["Clio"](https://tokinowa.fandom.com/wiki/Miime) and I took it because I couldn't come up with any better names myself.

**Comment by Ivo-Balbaert** [comment]
If I may go against the current, I very much like the name Clio because of its mythological connotations
( [Clio origin](https://en.wikipedia.org/wiki/Clio) ).
Nowadays it is virtually impossible to find a name which is not already used as a brand, even in software applications.
The Clio programming language is quite different from the Clio application software ( [Clio app](https://www.clio.com/) ).
Mentioning this on the website should be enough.
If a name change is really necessary, I suggest Kleio (keep the extension and original significance) or Klio (.klio).

**Comment by pouya-eghbali** [comment]
@Ivo-Balbaert I agree with that. I like the name, it's simple, sounds nice, and people already know it. Sure it's not good for SEO, but any name we choose people are going to have to add a "lang" when searching for it. I searched months for a name and I couldn't come up with a name that sounds good and is not taken. If we get into legal conflicts with Clio the app then we will change the name to Klio or Kleio as you suggested.

**Comment by pouya-eghbali** [comment]
Closing this, it took me a looong time to come up with Clio initially, this was just a hobby project at first, it still is but taken more seriously. I'm keeping the name, and as @Ivo-Balbaert suggested we will rename to Kleio or Klio in case of legal issues.
