### ISSUE TITLE
Split a string

### ISSUE THREAD

**Issue by fuzzthink** [clio-lang/clio#21]
How to split a string by char (or empty char) to an array?

**Comment by raphaelkieling** [comment]
Use `split` in flow process

`"hello world" -> split ""  -> print`

The js code is:
`console.log( "hello world".split(" ") )`

I use this for help u: [here](https://docs.clio-lang.org/learn/official-tutorial/flow)

**Comment by garritfra** [comment]
@raphaelkieling thanks for your reply!
@fuzzthink did that work for you? If that's the case, I would like to close this issue

**Comment by raphaelkieling** [comment]
it's simple issue, i think it may

**Comment by fuzzthink** [comment]
No, it didn't.
split.clio:
```
"hello world" -> split "" -> print
```

```
At file "split.clio" when calling print:

   1 │ "hello world" -> split "" -> print
                                    ^ At line 1 char 29

 Exception: BigInt is not defined
```

Also, how do i know `split` is available? Searching for `split` in source did not result in definition.

**Comment by fuzzthink** [comment]
Ah, issue was node was v8.15.0. Works with node v10.14.

I see `split` is native from javascript String.

**Comment by garritfra** [comment]
Clio compiles to JavaScript. All the methods are therefore just calls to native JS methods. `"hello world" -> split "" -> print` compiles to `"console.log(hello world".split(""))`

**Comment by raphaelkieling** [comment]
Your issues has bugs on compile functions, what is your clio version?

**Comment by raphaelkieling** [comment]
I used that code:
`"hello world" -> split "" -> print`

output:

![image](https://user-images.githubusercontent.com/16259523/56915363-ae13a700-6a8c-11e9-811c-aca6eb401d2b.png)

**Comment by pouya-eghbali** [comment]
I'm changing a few things here. First of all we'll not have

`"hello world" -> split ""`

instead we'll have 

`"hello world" -> .split ""`

I have a few reasons to do this, main reason is the complicated name resolution we have, it's a little confusing.

Second change is we'll call functions / methods directly, we will not have a `call_function` / `map_function` in built-ins.

Third change is, we'll not use Decimal / BigInt or any other big number library, we'll simply use JavaScript data types.

Instead of putting all the functional programming / lazy evaluation tools in Clio, we'll simply be an alternative syntax for JavaScript, however, we will provide libraries to do functional programming / lazy evaluation.

I know you're seeing lots of errors and weird behavior, I'm reworking how Clio works and I'm rewriting a huge part of the core, a lot of stuff are going to change, and hopefully we'll have a cleaner, better, faster Clio.

See #17 for more info about these changes.
